version: '3'
networks:
  net:
    driver: bridge
services:
  mongo:
    image: "mongo:3.6"
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=ant123
    networks:
     - net
    ports:
     - "27017:27017"
    volumes:
     - "c:/mongodb:/data/db"
  bot-api:
    build:
      context: ./
      dockerfile: DockerfileWebApi
    environment:
     - BOT_bot__token=asdasdasdasd
     - BOT_database__connectionString=mongodb://admin:ant123@crypt-bot_mongo_1:27017
    ports:
     - "8433:80"
    networks:
     - net
  bot-jobs:
    build:
      context: ./
      dockerfile: DockerfileJobsFnc
    environment:
     - BOT_bot__token=asdasdasdasd
     - BOT_database__connectionString=mongodb://admin:ant123@crypt-bot_mongo_1:27017
    networks:
     - net